spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://my-instance.ckhiau6owruk.us-east-1.rds.amazonaws.com:5432/test
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    locations:
      - classpath:db/migration/
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_EMPTY
    deserialization.fail-on-unknown-properties: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false